In [2]:
import numpy as np

In [23]:
import glob
import re

times_files = glob.glob("keyword_result/times/times*.npy")

keyword_times = {}
for f in times_files:
    time = np.load(f)
    query_name = re.search("keyword_result/times/times_jp_(\d+)\.npy", f)
    query_name = query_name.group(1)
    keyword_times[query_name] = time[0]

import json
with open("result_json/keyword_times.json", "w") as f:
    json.dump(keyword_times, f)

results_files = glob.glob("keyword_result/results/results*.npy")
keyword_result_list = []
for f in results_files:
    result = np.load(f).astype(int)
    keyword_result_list.append(result)
    query_name = re.search("keyword_result/results/results_jp_(\d+)\.npy", f)
    query_name = query_name.group(1)
    print(query_name)

keyword_result = np.array(keyword_result_list)
keyword_result[:, [0,3]]

1618
1325
1863
340
42
1504
1577
1824
679
859


array([[380, 380],
       [260, 260],
       [155, 155],
       [  2,   2],
       [620, 613],
       [192, 169],
       [  9,   9],
       [175, 174],
       [102, 102],
       [295, 295]])

In [25]:
times_files = glob.glob("attr_result/times/times*.npy")

attr_times = {}
for f in times_files:
    time = np.load(f)
    query_name = re.search("attr_result/times/times_jp_(\d+)\.npy", f)
    query_name = query_name.group(1)
    attr_times[query_name] = time[0]

import json
with open("result_json/attr_times.json", "w") as f:
    json.dump(attr_times, f)

results_files = glob.glob("attr_result/results/results*.npy")
attr_result_list = []
for f in results_files:
    result = np.load(f).astype(int)
    attr_result_list.append(result)
    query_name = re.search("attr_result/results/results_jp_(\d+)\.npy", f)
    query_name = query_name.group(1)
    print(query_name)

attr_result = np.array(attr_result_list)
attr_result[:, [0,3]]

1618
1325
1863
340
42
1504
1577
1824
679
859


array([[1043, 1043],
       [ 881,  881],
       [1030, 1030],
       [ 730,  730],
       [  41,   36],
       [   2,    2],
       [  11,   11],
       [   1,    1],
       [  11,   11],
       [1043, 1043]])

In [26]:
times_files = glob.glob("s4_result/times/times*.npy")

qbe_times = {}
for f in times_files:
    time = np.load(f)
    query_name = re.search("s4_result/times/times_jp_(\d+)\.npy", f)
    query_name = query_name.group(1)
    qbe_times[query_name] = time[0]

import json
with open("result_json/qbe_times.json", "w") as f:
    json.dump(qbe_times, f)

results_files = glob.glob("s4_result/results/results*.npy")
qbe_result_list = []
for f in results_files:
    result = np.load(f).astype(int)
    qbe_result_list.append(result)
    query_name = re.search("s4_result/results/results_jp_(\d+)\.npy", f)
    query_name = query_name.group(1)
    print(query_name)

qbe_result = np.array(qbe_result_list)
qbe_result[:, [0,3]]

1618
1325
1863
340
42
1504
1577
1824
679
859


array([[27562, 12017],
       [  170,    86],
       [ 5441,  3074],
       [    2,     2],
       [  541,    55],
       [ 5619,   859],
       [ 4791,  4467],
       [   93,     7],
       [ 7878,  7862],
       [  465,   241]])